Fix how the `Migration`s with custom state update are applied
SpineEventEngine/core-java pull request #1298
Opened 2020-09-02 21:10 UTC by dmitrykuzmin

This PR fixes #1297.

The root cause of the bug is a discrepancy between entity and underlying transaction versions in `Migration` when updating the entity state.

This PR thus adds the missing `setVersion(...)` call.

It also applies some refactoring to the `Migration` class. Its current logic is confusing, with entity updates being propagated partially in-place, partially on transaction commit. This leads to strange code paths and observed values when debugging.

Now, all entity changes will be propagated on transaction commit at the very end of `Migration.applyTo(...)`.

2020-09-02 21:57 UTC, dmitrykuzmin commented
@armiol, @yuri-sergiichuk PTAL.

2020-09-03 08:55 UTC, yuri-sergiichuk requested changes
@dmitrykuzmin PTAL at the comments below.

2020-09-03 08:55 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/procman/ProcessManagerRepositoryTest.java
> +                    .isEqualTo(eventMessage.getProjectId());
Why do we compare only the IDs here and below? Can we just hand-craft the expected message and compare the whole message instead?

2020-09-03 08:55 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/procman/ProcessManagerRepositoryTest.java
> +                                    .getIdString()).isEqualTo(id.toString());
I'd actually compare `state` and not the ID only.

2020-09-03 08:55 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/projection/given/SetTestProjectionName.java
> + * A migration which sets the projection name to a predefined {@linkplain #NEW_NAME value}.
```suggestion
 * Sets the projection {@code name} to a predefined {@linkplain #NEW_NAME value}.
```

2020-09-03 08:55 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/procman/given/repo/SetTestProcessName.java
> + * A migration which sets the process name to a predefined {@linkplain #NEW_NAME value}.
```suggestion
 * Sets the process {@code name} to a predefined {@linkplain #NEW_NAME value}.
```

2020-09-03 08:55 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/procman/given/repo/SetTestProcessName.java
> +    public static final String NEW_NAME = "Migrated project";
Maybe `Migrated process`? You have `Migrated projection` in the projection migration below.

2020-09-03 08:55 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/procman/ProcessManagerRepositoryTest.java
>          assertThat(found.isPresent()).isTrue();
There's a whole set of `Truth8` assertions that should allow having a bit nicer syntax for `Optional`s. Could you please check it out and consider using them instead?

2020-09-03 08:55 UTC, yuri-sergiichuk commented on server/src/main/java/io/spine/server/entity/Migration.java
>          private @MonotonicNonNull Event systemEvent;
Same for `@LazyInit`. It looks like we should add the annotation to the `systemEvent` as well.

2020-09-03 08:55 UTC, yuri-sergiichuk commented on server/src/main/java/io/spine/server/entity/Migration.java
>          private boolean physicallyRemoveRecord;
In the `Operation` docs it states that it's the operation done on an entity instance. In fact, we apply the migration to the `tx().builder()` now, right?

I guess it really worth adding some more details on how the migration operation is actually being done while you're in the context now.

2020-09-03 12:32 UTC, dmitrykuzmin commented
@yuri-sergiichuk PTAL again.

2020-09-03 14:43 UTC, yuri-sergiichuk requested changes
@dmitrykuzmin PTAL at the comments.

2020-09-03 14:43 UTC, yuri-sergiichuk commented on server/src/main/java/io/spine/server/entity/Migration.java
> +     * @see Operation Migration.Operation for details
This `see` section looks redundant. You have the very same link as for `operation`. I'd better remove it.

2020-09-03 14:43 UTC, yuri-sergiichuk commented on server/src/main/java/io/spine/server/entity/Migration.java
> +     * Applies the migration {@linkplain Operation operation} to a given entity.
```suggestion
     * Applies the migration {@linkplain Operation operation} to a given {@code entity}.
```

2020-09-03 14:43 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/bus/BusFilterTest.java
> +        Truth8.assertThat(ack).isEmpty();
Please import `assertThat` statically here and in the other places.

2020-09-03 14:43 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/procman/ProcessManagerRepositoryTest.java
> +        assertThat(entityWithColumns.state()
Can we please have expected state here as well?

2020-09-03 14:43 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/procman/ProcessManagerRepositoryTest.java
> +        Truth8.assertThat(found).isPresent();
Please use static imports.

2020-09-03 14:43 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/procman/ProcessManagerRepositoryTest.java
> +        return projection.id()
Let's flip the params. You'll then be able to have them on the same line.

2020-09-03 14:43 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/projection/ProjectionRepositoryTest.java
> +                .containsExactly(id1, id2);
Can we test states here as well?

2020-09-03 14:43 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/projection/ProjectionRepositoryTest.java
> +        Truth8.assertThat(found).isPresent();
Please use static imports.

2020-09-03 17:10 UTC, dmitrykuzmin commented
@yuri-sergiichuk PTAL again.

2020-09-03 18:05 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/procman/ProcessManagerRepositoryTest.java
> +                .containsExactly(pm1, pm2);
So the migration does nothing? We're comparing the results to the same PMs we've manually stored.

2020-09-03 18:05 UTC, yuri-sergiichuk commented on server/src/test/java/io/spine/server/procman/ProcessManagerRepositoryTest.java
> +                .containsExactly(pm1, pm2);
OK, now I see that inside the correspondence we actually manually change the state of the PMs to match the actual one. It looks a bit too complicated...

2020-09-03 18:07 UTC, yuri-sergiichuk approved these changes
@dmitrykuzmin in general LGTM.

I'd prefer to have a bit more straight-forward states comparison.

2020-09-04 13:24 UTC, merged