Allow inherited methods with generics and Kotlin methods as signal handlers
SpineEventEngine/core-java pull request #1366
Opened 2021-05-19 14:49 UTC by dmdashenkov

In this PR we adjust the method scanning process.

## Generics and inheritance

In Java, when overriding a method that accepts a parameter of a generic type with a method that accepts a parameter with a concrete type, the compiler, for technical reasons, generates a "bridge" method with a similar signature and the same annotations.
If such a method is made a signal handler (by adding an annotation), an error occurred, as the bridge method was also found to be a handler. For example:
```java
interface MyFancySubscriber<E extends EventMessage> {

    void on(E event);
}

class MyFancyImpl implements MyFancySubscriber<ProjectCreated> {

    @Override
    @Subscribe
    void on(ProjectCreated event) { ... }

    // Here, the compiler generates a bridge method:
    //
    // @Override
    // @Subscribe
    // void on(EventMessage event) {
    //     on((ProjectCreated) event);
    // }
}
```

Before this PR, Spine used to fail to scan such a class, as `on(EventMessage)` is not a valid subscriber. Now, we ignore all the compiler-generated methods.

## Kotlin and package-private

When writing a signal handler class (an abstract subscriber, handler, reactor, or commander, or an entity) in Kotlin, the developer always had to deal with console warnings informing them that the used access modifier is incorrect and they should use "package-private" instead. Kotlin, of course, does not have "package-private" visibility.

Starting from this PR, Kotlin users will be able to use `internal` wherever Spine requires "package-private". That is, all the signal handler methods, except event appliers, which ought to be private regardless of the source language.

2021-05-19 15:07 UTC, armiol requested changes
@dmdashenkov please see my comments.

2021-05-19 15:07 UTC, armiol commented on server/src/main/java/io/spine/server/model/J2Kt.java
> +final class J2Kt {
As discussed, let's move this utility to some place in `base`, as it hardly belongs to `server.model`.

2021-05-19 15:07 UTC, armiol commented on server/src/main/java/io/spine/server/model/J2Kt.java
> +    static Optional<KCallable<?>> findKotlinMethod(Method javaMethod) {
Again, as discussed, let's document this method and, also, check for `null` values.

2021-05-24 09:45 UTC, dmdashenkov commented
@armiol, PTAL.

2021-05-24 10:53 UTC, armiol approved these changes

2021-05-24 11:45 UTC, merged