Enable IntegrationBroker dispatch events regardless of registration order of subscribing and publishing BCs
SpineEventEngine/core-java pull request #1408
Opened 2021-10-28 14:45 UTC by yevhenii-nadtochii

It's a migration of #1402 to the 2.x branch.

Additionally, the code has been migrated to the latest `McJavaOptions`. The versions of the dependencies were set to the latest available.

2021-11-01 17:52 UTC, alexander-yevsyukov commented on server/src/main/java/io/spine/server/integration/AbstractChannelObserver.java
> + * subscriber observers.
This change needs to remove either preceeding `}` so that `linkplain` works, or, make `likplain` be just `link`.

2021-11-01 17:54 UTC, alexander-yevsyukov commented on server/src/main/java/io/spine/server/integration/ExternalMessages.java
> +        return StringValue.newBuilder()
Why don't we employ the luxury of `StringValue.of()` here?

2021-11-02 15:12 UTC, alexander-yevsyukov requested changes
Please see my comments.

2021-11-11 18:34 UTC, armiol commented
@yevhenii-nadtochii FYI. For some reason, I am not able to request a review from you. Probably, because you are the original author. However, should you have any comments/questions, let's discuss those vocally.

2021-11-11 20:56 UTC, alexander-yevsyukov reviewed
Please see some minor comments. Will continue reviewing tomorrow.

2021-11-11 20:56 UTC, alexander-yevsyukov commented on server/src/main/java/io/spine/server/BoundedContextBuilder.java
> +     * {@link io.spine.server.integration.IntegrationBroker} after the Bounded Context creation.
Can we have a short name of the class following the fully-qualified name in the link, please?

2021-11-11 20:56 UTC, alexander-yevsyukov commented on server/src/main/java/io/spine/server/integration/ConfigExchange.java
> +                .newBuilder()
Please have `.newBuilder()` on the previous line.

2021-11-11 20:56 UTC, alexander-yevsyukov commented on server/src/main/java/io/spine/server/integration/ConfigExchange.java
> +        for (ObserveWantedEvents observer : observers) {
Can we have `forEach()` here, please?

2021-11-11 20:56 UTC, alexander-yevsyukov commented on server/src/main/java/io/spine/server/integration/EventsExchange.java
> +class EventsExchange extends AbstractExchange {
`final`?

2021-11-12 10:31 UTC, alexander-yevsyukov approved these changes
LGTM, with few minor comments to address

2021-11-12 10:31 UTC, alexander-yevsyukov commented on server/src/main/java/io/spine/server/integration/EventsExchange.java
> +    @Internal
Do we really need this annotation, assuming that the class is package-private?

2021-11-12 10:31 UTC, alexander-yevsyukov commented on server/src/main/java/io/spine/server/integration/EventsExchange.java
> +        checkNotNull(cls);
This null check looks as excessive, assuming we're doing it in `private static` method, and the next line calls a method of the passed object, anyway.

2021-11-12 12:00 UTC, yevhenii-nadtochii reviewed
Please see my questions

2021-11-12 12:00 UTC, yevhenii-nadtochii commented on server/src/main/java/io/spine/server/integration/AbstractExchange.java
> +abstract class AbstractExchange {
This class seems to `implements TransportLink` by delegation with no own functionality. Is this for API usability / naming?

2021-11-12 12:00 UTC, yevhenii-nadtochii commented on server/src/main/java/io/spine/server/integration/ConfigExchange.java
> +     * Routine that peforms the broadcast from this Context to other Bounded Contexts.
a typo `performs`

2021-11-12 12:00 UTC, yevhenii-nadtochii commented on server/src/main/java/io/spine/server/integration/IntegrationBroker.java
>          publisherHub.close();
`IntegrationBroker` seems not to be a main holder and user of these resources. Could we drop these fields from this class and store `TransportLink : Closeable` instead?

2021-11-12 12:00 UTC, yevhenii-nadtochii commented on server/src/main/java/io/spine/server/integration/TransportLink.java
> +     *         the hub of {@code Publisher}s
Why to write docs that duplicate names of Type and parameter? Is this a `javadoc` tool restriction? I mean situations, in which not all parameters really need documentation.

2021-11-12 13:25 UTC, merged