Do not log thrown `Error`
SpineEventEngine/core-java pull request #1561
Opened 2024-12-14 16:16 UTC by alexander-yevsyukov

This PR updates the behaviour of `Bus.doPost()` to avoid logging instances of `Error` thrown during dispatching. This modification continues special treatment of `Error` which are [propagate](1560) instead of recording in dispatching outcome.

2024-12-14 22:34 UTC, alexander-yevsyukov commented
@armiol, PTAL.

2024-12-15 11:31 UTC, armiol requested changes
@alexander-yevsyukov LGTM except for a comment.

2024-12-15 11:31 UTC, armiol commented on server/src/main/java/io/spine/server/bus/Bus.java
> +     * <p>We treat {@link Error}s differently and want to void much of console output
We treat `Mistake`s differently. Is that what you meant?

2024-12-15 11:32 UTC, armiol commented
@alexander-yevsyukov also, the license report check failed. JFYI.

2024-12-15 13:18 UTC, armiol commented
@alexander-yevsyukov 
```
     * Please see {@link io.spine.server.model.AbstractReceptor#invoke(Object, MessageEnvelope)}
     * for more details on special treatment of {@link Error} during dispatching.
 ```

There's still about `Error`s. Not about `Mistake`s.

2024-12-15 13:26 UTC, armiol requested changes

2024-12-15 13:26 UTC, armiol commented on server/src/main/java/io/spine/server/bus/Bus.java
> +     * for more details on special treatment of {@link Error} during dispatching.
Same as previously. It should be `Mistake`.

2024-12-15 13:26 UTC, armiol commented on server/src/main/java/io/spine/server/bus/Bus.java
> +     * for more details on special treatment of {@link Message} during dispatching.
Should be
```
for more details on special treatment of {@link Mistake} during dispatching.
```

2024-12-15 13:48 UTC, armiol commented
@alexander-yevsyukov please see my [last comment](https://github.com/SpineEventEngine/core-java/pull/1561/files#r1885704644). It's not addressed yet.

2024-12-15 13:55 UTC, armiol approved these changes

2024-12-15 14:48 UTC, merged